/**
 * Tipos de erro da API
 */
export interface ErrorResponse {
  error: {
    code: string;
    message: string;
    timestamp: string;
    traceId: string;
    details?: Record<string, unknown>;
  };
}

/**
 * Códigos de erro do sistema (espelhando backend)
 */
export const ErrorCodes = {
  // AUTH_ - Autenticação
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_USER_PENDING: 'AUTH_USER_PENDING',
  AUTH_USER_SUSPENDED: 'AUTH_USER_SUSPENDED',
  AUTH_USER_REJECTED: 'AUTH_USER_REJECTED',
  AUTH_USER_INACTIVE: 'AUTH_USER_INACTIVE',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FIREBASE_ERROR: 'AUTH_FIREBASE_ERROR',

  // VAL_ - Validação
  VAL_REQUIRED_FIELD: 'VAL_REQUIRED_FIELD',
  VAL_INVALID_EMAIL: 'VAL_INVALID_EMAIL',
  VAL_INVALID_DATE: 'VAL_INVALID_DATE',
  VAL_INVALID_AMOUNT: 'VAL_INVALID_AMOUNT',
  VAL_INVALID_TYPE: 'VAL_INVALID_TYPE',
  VAL_INVALID_LENGTH: 'VAL_INVALID_LENGTH',
  VAL_INVALID_RANGE: 'VAL_INVALID_RANGE',
  VAL_INVALID_FORMAT: 'VAL_INVALID_FORMAT',
  VAL_DUPLICATE_VALUE: 'VAL_DUPLICATE_VALUE',
  VAL_INVALID_REFERENCE: 'VAL_INVALID_REFERENCE',

  // FIN_ - Regras Financeiras
  FIN_TRANSACTION_NOT_FOUND: 'FIN_TRANSACTION_NOT_FOUND',
  FIN_CATEGORY_NOT_FOUND: 'FIN_CATEGORY_NOT_FOUND',
  FIN_PERIOD_CLOSED: 'FIN_PERIOD_CLOSED',
  FIN_INVALID_AMOUNT: 'FIN_INVALID_AMOUNT',
  FIN_INVALID_DATE: 'FIN_INVALID_DATE',
  FIN_DUPLICATE_TRANSACTION: 'FIN_DUPLICATE_TRANSACTION',
  FIN_CATEGORY_IN_USE: 'FIN_CATEGORY_IN_USE',
  FIN_TRANSACTION_ALREADY_DELETED: 'FIN_TRANSACTION_ALREADY_DELETED',
  FIN_CATEGORY_ALREADY_DELETED: 'FIN_CATEGORY_ALREADY_DELETED',
  FIN_BALANCE_MISMATCH: 'FIN_BALANCE_MISMATCH',
  FIN_FUTURE_DATE: 'FIN_FUTURE_DATE',
  FIN_INVALID_PERIOD: 'FIN_INVALID_PERIOD',

  // PERM_ - Permissões
  PERM_ACCESS_DENIED: 'PERM_ACCESS_DENIED',
  PERM_INSUFFICIENT_PERMISSIONS: 'PERM_INSUFFICIENT_PERMISSIONS',
  PERM_INSUFFICIENT_PRIVILEGES: 'PERM_INSUFFICIENT_PRIVILEGES',
  PERM_INVALID_ROLE: 'PERM_INVALID_ROLE',

  // USER_ - Gestão Usuários
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INVALID_STATUS_TRANSITION: 'USER_INVALID_STATUS_TRANSITION',
  USER_STATUS_REQUIRED: 'USER_STATUS_REQUIRED',
  USER_STATUS_REASON_REQUIRED: 'USER_STATUS_REASON_REQUIRED',
  USER_STATUS_REASON_TOO_LONG: 'USER_STATUS_REASON_TOO_LONG',
  USER_INVALID_STATUS: 'USER_INVALID_STATUS',
  USER_CANNOT_MODIFY_OWN_STATUS: 'USER_CANNOT_MODIFY_OWN_STATUS',
  USER_CANNOT_REMOVE_OWN_ADMIN: 'USER_CANNOT_REMOVE_OWN_ADMIN',
  USER_LAST_ADMIN: 'USER_LAST_ADMIN',
  USER_ROLES_REQUIRED: 'USER_ROLES_REQUIRED',
  USER_ROLE_EMPTY: 'USER_ROLE_EMPTY',
  USER_INVALID_ROLE: 'USER_INVALID_ROLE',

  // SYS_ - Sistema
  SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
  SYS_SERVICE_UNAVAILABLE: 'SYS_SERVICE_UNAVAILABLE',
  SYS_MAINTENANCE: 'SYS_MAINTENANCE',

  // INT_ - Integrações
  INT_FIREBASE_ERROR: 'INT_FIREBASE_ERROR',
  INT_DATABASE_ERROR: 'INT_DATABASE_ERROR',
  INT_EXTERNAL_SERVICE_ERROR: 'INT_EXTERNAL_SERVICE_ERROR',

  // EXPORT_ - Exportações
  EXPORT_NOT_FOUND: 'EXPORT_NOT_FOUND',
  EXPORT_GENERATION_FAILED: 'EXPORT_GENERATION_FAILED',
  EXPORT_FORMAT_NOT_SUPPORTED: 'EXPORT_FORMAT_NOT_SUPPORTED',
  EXPORT_PERIOD_TOO_LARGE: 'EXPORT_PERIOD_TOO_LARGE',
  EXPORT_NO_DATA: 'EXPORT_NO_DATA',
  EXPORT_PERMISSION_DENIED: 'EXPORT_PERMISSION_DENIED',
  EXPORT_INVALID_PARAMETERS: 'EXPORT_INVALID_PARAMETERS',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/**
 * Classe de erro customizada para erros da API
 */
export class ApiError extends Error {
  constructor(
    public code: string,
    message: string,
    public traceId?: string,
    public details?: Record<string, unknown>
  ) {
    super(message);
    this.name = 'ApiError';
  }
}
